### ISSUE TITLE
Portals: Implementation tracker

### ISSUE THREAD

**Issue by ENDERZOMBI102** [ENDERZOMBI102/PortalBase#1]
- [ ] Entity interaction
	- [ ] Teleport
	- [ ] Show on other side
	- [ ] Duplicate hitbox
	- [ ] Entity-in-portal interaction
	- [ ] Entities can see via portals
	- [ ] Portal projectiles
- [ ] Rendering
	- [ ] Render world in portal
	- [ ] Occlude stuff from non-visible areas
	- [ ] Particles
- [ ] Engine interactions
	- [ ] Disable collision for brush behind portal
	- [ ] Rays go though portals
	- [ ] Bullets go through portals
